dependencies {
    // Anvil Lib
    implementation(libs.anvillib)
    // interfaceInjectionData(libs.anvillib)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // Kaleidoscope
    implementation(libs.kaleidoscopeCookery)
    implementation(libs.kaleidoscopeDoll)
}